### ISSUE TITLE
[BUG] <PGAP Fail on AWS Batch>

### ISSUE THREAD

**Issue by kpenn88** [ncbi/pgap#204]
**Describe the bug**
I am running PGAP on AWS and yet it is failing, it was working fine with the previous version but the new version is failing. 
I am trying to determine:
Why the CWL process is failing
Where we could get more information on the failure if required.

I am attaching the error log
[cwl-debug (1).zip](https://github.com/ncbi/pgap/files/8764515/cwl-debug.1.zip)

**Comment by azat-badretdin** [comment]
Thanks for your report, Kevin! Could you please post `cwltool.log`?

**Comment by kpenn88** [comment]
Sorry we had to rerun here are the cwltool.log and the debug/tmp-outdir/*/*.lo
[cwltool.log](https://github.com/ncbi/pgap/files/8775568/cwltool.log)
[ncbiapp.log](https://github.com/ncbi/pgap/files/8775571/ncbiapp.log)
g

**Comment by azat-badretdin** [comment]
You are using 2022-02-10.build5872. The problem has been fixed in the recent release, please reinstall PGAP.

**Comment by kpenn88** [comment]
We reran us the newest build see attached, still fail
[output.zip](https://github.com/ncbi/pgap/files/8800568/output.zip)
s

**Comment by kpenn88** [comment]
Since this is via aws each run is a fresh install.

**Comment by azat-badretdin** [comment]
Thanks, Kevin!

Since you are using `--no-internet` option on the second run, it does not download missing reference data components. 

Please run your installation line with `--taxcheck` option as well.

**Comment by azat-badretdin** [comment]
Did you run 

```
./pgap.py --update --taxcheck

```
that's what I meant by 

```

Please run your installation line with --taxcheck option as well

```

If you did not, it's my fault. Confusing instruction on my part. 

Thanks!

**Comment by azat-badretdin** [comment]
> So another issue that's potentially unrelated

Let's first wrap up the previous issue. 

Did you run

```

./pgap.py --update --taxcheck

```

**Comment by steve3492** [comment]
```
/ # /bin/ls -lar ~/.pgap/
total 8
drwxr-xr-x   27 9015     562           4096 Jun  7 17:17 test_genomes-2022-04-14.build6021
lrwxrwxrwx    1 9015     562             33 Jun  7 17:17 test_genomes -> test_genomes-2022-04-14.build6021
drwxr-xr-x   11 root     root          4096 Jun  7 17:26 input-2022-04-14.build6021
drwx------    1 root     root            39 Jun  7 17:17 ..
drwxr-xr-x    4 root     root           101 Jun  7 17:17 .
/ # 
```

Copy of pgap.py we're running:
[pgap copy.py.txt](https://github.com/ncbi/pgap/files/8855306/pgap.copy.py.txt)

**Comment by azat-badretdin** [comment]
Thanks for a quick reply. Alas I made a typo and requested `ls -lar` instead of `ls -laR` (recursive listing). Would you mind posting that as well, as an attachment? Many apologies.

**Comment by steve3492** [comment]
[pgap-inputs-listing_7-Jun-2022.txt](https://github.com/ncbi/pgap/files/8856033/pgap-inputs-listing_7-Jun-2022.txt)
Yes sir, as requested.

**Comment by azat-badretdin** [comment]
Thank you very much. This, unfortunately, eliminates most common source of this class of problems from the past: underdownloading reference data.

You have reference data, you have mounted it to the docker instance in the correct place (~/.pgap) 

The crucial difference starts here:

Your `cwltool.log` reports (thank you very much, `--debug` option):

```

[2022-06-07 14:17:31] DEBUG [step passdata] job input {
    "file:///pgap/pgap/taxcheck.cwl#passdata/data": {
        "class": "Directory",
        "location": "file:///pgap/input",
        "basename": "input",
        "listing": []
    }
}

```

the proper echo of the job input (btw, also on AWS) is (not in the same place, but completely analogous place):

```

    "supplemental_data": {
        "class": "Directory",
        "location": "file:///pgap/input",
        "basename": "input",
        "listing": [
            {
                "class": "Directory",
....

```
That indicates that docker mount to `/pgap/input` entry that is passed to `cwltool` is somehow unreadable from inside the docker instance.

That potentially indicates to some peculiarities of your docker setup on your AWS host. 

I suggest that we shift now the focus from `pgap.py` to lower level `docker run` exploration, starting with straightforward attempt to list the contents of the reference data directory on your host. 

```

/usr/local/bin/docker run -i --rm --user 0:0 --volume /root/.pgap/input-2022-04-14.build6021:/pgap/input:ro,z --volume /mnt/root/2ed6bd6b-0a3f-5ac3-b7e9-e67250e25897FB0SZ4Z88T1WMPEE0012520e1c660d06d778e32cb03f4b23:/pgap/user_input:z --volume /mnt/root/2ed6bd6b-0a3f-5ac3-b7e9-e67250e25897FB0SZ4Z88T1WMPEE0012520e1c660d06d778e32cb03f4b23/pgap_input_98n1gwps.yaml:/pgap/user_input/pgap_input.yaml:ro,z --volume /tmp:/tmp:rw,z --volume /mnt/root/2ed6bd6b-0a3f-5ac3-b7e9-e67250e25897FB0SZ4Z88T1WMPEE0012520e1c660d06d778e32cb03f4b23/MP16566:/pgap/output:rw,z --volume /mnt/root/2ed6bd6b-0a3f-5ac3-b7e9-e67250e25897FB0SZ4Z88T1WMPEE0012520e1c660d06d778e32cb03f4b23/MP16566/debug/log:/log/srv:z ncbi/pgap:2022-04-14.build6021 \
     ls -laR /pgap/input/

```
I presume that you can revive the AWS host used for your typical PGAP test. If you will use new host you will have to replace the randomly generated directory names from already extinct host in this call with actual directory names from the host you can get in. 

Is this test possible in your automated AWS setup? 

If this generates no listing, then I suggest to look for the cause of the problem on your docker settings on your AWS machine.

**Comment by steve3492** [comment]
Thanks very much Azat, let me think of what changes we'll need to make to test this out.

**Comment by azat-badretdin** [comment]
> we have a similar bulk processing setup on GPC

At this moment the code for that setup is internal only due to high specificity of actions in that setup. But we can share high level details if necessary.

**Comment by steve3492** [comment]
I believe you've found it. It looks like the `/root/.pgap/input-2022-04-14.build6021` directory is not getting linked to the container which is trying to run the `cwltool` job. Below is the docker log from the command you recommended above. I confirmed this by hand by not removing the host as well & checking by hand, as well as logging onto the `cwltool` container & verifying there as well:
```
/pgap/input/:
total 0
drwxr-xr-x 2 root root  6 Jun 13 19:59 .
drwxr-xr-x 1 root root 19 Apr 14 19:15 ..
```

I've also attached two docker inspections, one for the base pgap container (the one executing the `pgap.py` calls which downloads the data, etc), and one for the container where the `cwltool` command is being executed from.

[base_pgap_container_inspection.txt](https://github.com/ncbi/pgap/files/8894209/base_pgap_container_inspection.txt)
[cwltool_container_inspection.txt](https://github.com/ncbi/pgap/files/8894210/cwltool_container_inspection.txt)

You can see the volumes being listed as attempted to be mounted, and what's odd is the rest of them seem to be mounting. It's just the `/pgap/inputs/` which is failing to be seen properly.

Going to poke around some more on our end to see if there is a config setting which may be preventing this, but wanted to let you know.

I should also mention (may or may not be relevant): our last successful run was on `2021-11-29.build5742`.

**Comment by azat-badretdin** [comment]
> our last successful run was on 2021-11-29.build5742.

That's very relevant, thanks for mentioning. "Something changed" is important to know (compared to "we were never been able to make it work") 

The closest change we did was that we moved the default installation path from current directory to `~/.pgap` 

That immediately generates the idea that seems to be easy to test. What if you change installation path in your AWS host setup to point to the "old" place by specifying the ENV path to the "current" directory (you can find how to do that on this page: https://github.com/ncbi/pgap/wiki/Quick-Start)? 

If that works then it could be some local docker settings that differentiate between different locations.

**Comment by steve3492** [comment]
....and right on cue we get a run. We've made some progress, but there are still errors.

Editing the `PGAP_INPUT_DIR` seems to have fixed the mount issue, where now the test genome data gets carried over.
[Uploading cwltools-dir-listing_15-Jun-2022.txt…]()

(Docker inspect for reference as well: [cwltools-inspect_15-Jun-2022.txt](https://github.com/ncbi/pgap/files/8912749/cwltools-inspect_15-Jun-2022.txt))

That said, we're getting the following error from PGAP itself now:
```
[2022-06-15 20:03:17,509] {execute_pgap.py:137} WARNING - b'PGAP version 2022-04-14.build6021 is up to date.
Output will be placed in: /mnt/root/9468b103-1d2a-5349-bc6f-ea272bbd7b65564EBZ6GFX1KQABQ1e167c52cc7e2d88da1f560880f8bda3/XXXXXXX
WARNING: work disk space (GiB) is less than the recommended value of 80
TAXCHECK completed successfully.
ERROR: taxcheck failed to assign a species with high confidence, thus PGAP will not execute. See MP16566/ani-tax-report.txt
```

I captured some of the commands being executed, including where the one I believe it's failing on:
[cwltools-commands_15-Jun-2022.txt](https://github.com/ncbi/pgap/files/8912766/cwltools-commands_15-Jun-2022.txt)


Unfortunately I was not able to get the `ani-tx-report.txt` from this run, but can look to grab it in future ones.

Cheers,

**Comment by steve3492** [comment]
I also didn't grab the `cwltool.log` from that run, but here is the log from another run which errored out in the same fashion:
[cwltool.log](https://github.com/ncbi/pgap/files/8912838/cwltool.log)

**Comment by thibaudnis** [comment]
As the message says, the taxonomy verification step is unable to assign a species to the genome with confidence, so the process stops. If you are reasonably sure that the organism that you assigned to the genome is correct, try running without the `--auto-correct-tax` flag (and without `--taxcheck` too since you already know what the results are going to be).

**Comment by steve3492** [comment]
> As the message says, the taxonomy verification step is unable to assign a species to the genome with confidence, so the process stops. If you are reasonably sure that the organism that you assigned to the genome is correct, try running without the `--auto-correct-tax` flag (and without `--taxcheck` too since you already know what the results are going to be).

Will give that a shot, thanks for the feedback.

**Comment by steve3492** [comment]
Just wanted to update: we're still testing. We've had a successful run, and some more failures at different spots we're trying to isolate.

**Comment by steve3492** [comment]
I am calling this resolved from our end.
Most significantly, adding the `INPUT_PGAP_DIR` changed the mounting issues were experiencing within the containers themselves. That was the main cause of our pipelines breaking down. There was a couple other minor revisions we made to accounts for some filesystem handling, but these didn't impact in the same manner.

In the interest of full disclosure, we're still experiencing intermittent issues downloading the test genome data. We can supplement our end with some caching & additional checks to ease this, though.

Very much appreciate the work looking into this.

**Comment by azat-badretdin** [comment]
I am glad it's working around (if not out) for you. As for this:

> we're still experiencing intermittent issues downloading the test genome data

I am afraid this part is less under our control here at PGAP group, as a workaround I would suggest to download it once per release into your own more reliable location and use it as a backup. And I guess that's what you meant here:

> We can supplement our end with some caching & additional checks to ease this, though.

> Very much appreciate the work looking into this

We were glad to help!
